# .streamlit/secrets.toml

[connections.snowflake]
account = "PFKUVMC.AI42355"
user = "MDLANDI"
password = "hwLJJq6#f3kmN2Oi"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "smoothies"
schema = "public"
client_session_keep_alive = true
